Update patch set 1
Patch Set 1:

Should I skip the presubmit?

I think the error:
Error: the following files need to be regenerated: luci-scheduler.cfg.
  Run `lucicfg generate "config.star"` to update them.

is caused by the fact that I am not adding a CI bot?

Patch-set: 1
Reviewer: Gerrit User 5087 <5087@58829da1-049c-39fb-b951-ebdcd0984767>
Label: Commit-Queue=0