Update patch set 3
Patch Set 3:

> Patch Set 3:
> 
> > Patch Set 3:
> > 
> > > Patch Set 2:
> > > 
> > > > Patch Set 2:
> > > > 
> > > > Friendly ping :). Planning any more work on this?
> > > 
> > > Hi, Kári.
> > > 
> > > Yes, I'm going to finish this one. I've initially tried to move tests to xctest as you've asked and got stuck with linker error, which I failed to resolve quickly. Then lots of urgent tasks come from my primary job and I was disrupted from fixing this CL. Today I think I'll have time to work on this issue, so I'll try to complete migration to XCTest.
> > > 
> > > BTW, maybe you just know right away what could cause such error? I've just made this changes to existing test [1] (referenced RTCConfiguration class from RTCCallbackLogger_xctest.m, I did the same for newly added xctest file and got the same error, then when attempted to find out how to fix it and checked if the same error happens with existing tests) and got such error [2].
> > > The proper architecture and target name I use was found by trying to "derive" it from sdk/BUILD.gn, but maybe I did it wrong.
> > > 
> > > Thanks in advance,
> > > Yura.
> > > 
> > > [1]
> > > diff --git a/sdk/objc/Framework/UnitTests/RTCCallbackLogger_xctest.m b/sdk/objc/Framework/UnitTests/RTCCallbackLogger_xctest.m
> > > index f8bb879b4f..f4dd9a5fca 100644
> > > --- a/sdk/objc/Framework/UnitTests/RTCCallbackLogger_xctest.m
> > > +++ b/sdk/objc/Framework/UnitTests/RTCCallbackLogger_xctest.m
> > > @@ -9,6 +9,7 @@
> > >   */
> > > 
> > >  #import "WebRTC/RTCCallbackLogger.h"
> > > +#import "WebRTC/RTCConfiguration.h"
> > > 
> > >  #import <XCTest/XCTest.h>
> > > 
> > > @@ -32,6 +33,8 @@ - (void)tearDown {
> > > 
> > >  - (void)testCallbackGetsCalledForAppropriateLevel {
> > >    self.logger.severity = RTCLoggingSeverityWarning;
> > > +  RTCConfiguration *config = [RTCConfiguration new];
> > > +  config = nil;
> > > 
> > >    XCTestExpectation *callbackExpectation = [self expectationWithDescription:@"callbackWarning"];
> > > 
> > > [2]
> > > ➜  src git:(webrtc-9231-1) ✗ ninja -C out/ios_x64_debug sdk_unittests
> > > ninja: Entering directory `out/ios_x64_debug'
> > > [1/6] LINK obj/sdk/x64/sdk_unittests
> > > FAILED: obj/sdk/x64/sdk_unittests
> > > TOOL_VERSION=1527597445 ../../build/toolchain/mac/linker_driver.py ../../third_party/llvm-build/Release+Asserts/bin/clang++  -all_load -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -objc_abi_version -Xlinker 2 -Xlinker -sectcreate -Xlinker __TEXT -Xlinker __entitlements -Xlinker obj/sdk/sdk_unittests.xcent -arch x86_64 -Werror -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.4.sdk -stdlib=libc++ -mios-simulator-version-min=9.0 -Wl,-ObjC -F /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/Frameworks -o "obj/sdk/x64/sdk_unittests" -Wl,-filelist,"obj/sdk/x64/sdk_unittests.rsp"  -framework UIKit -framework CoreFoundation -framework CoreGraphics -framework CoreText -framework Foundation -framework XCTest -framework CFNetwork -framework Security -framework SystemConfiguration -framework AVFoundation -framework AudioToolbox -framework GLKit -framework OpenGLES -framework QuartzCore -framework CoreMedia -framework CoreVideo -framework VideoToolbox
> > > Undefined symbols for architecture x86_64:
> > >   "_OBJC_CLASS_$_RTCConfiguration", referenced from:
> > >       objc-class-ref in RTCCallbackLogger_xctest.o
> > > ld: symbol(s) not found for architecture x86_64
> > > clang: error: linker command failed with exit code 1 (use -v to see invocation)
> > > Traceback (most recent call last):
> > >   File "../../build/toolchain/mac/linker_driver.py", line 229, in <module>
> > >     Main(sys.argv)
> > >   File "../../build/toolchain/mac/linker_driver.py", line 79, in Main
> > >     subprocess.check_call(compiler_driver_args)
> > >   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
> > >     raise CalledProcessError(retcode, cmd)
> > > subprocess.CalledProcessError: Command '['../../third_party/llvm-build/Release+Asserts/bin/clang++', '-all_load', '-Xlinker', '-rpath', '-Xlinker', '@executable_path/Frameworks', '-Xlinker', '-rpath', '-Xlinker', '@loader_path/Frameworks', '-Xlinker', '-rpath', '-Xlinker', '@executable_path/Frameworks', '-Xlinker', '-objc_abi_version', '-Xlinker', '2', '-Xlinker', '-sectcreate', '-Xlinker', '__TEXT', '-Xlinker', '__entitlements', '-Xlinker', 'obj/sdk/sdk_unittests.xcent', '-arch', 'x86_64', '-Werror', '-isysroot', '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.4.sdk', '-stdlib=libc++', '-mios-simulator-version-min=9.0', '-Wl,-ObjC', '-F', '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/Frameworks', '-o', 'obj/sdk/x64/sdk_unittests', '-Wl,-filelist,obj/sdk/x64/sdk_unittests.rsp', '-framework', 'UIKit', '-framework', 'CoreFoundation', '-framework', 'CoreGraphics', '-framework', 'CoreText', '-framework', 'Foundation', '-framework', 'XCTest', '-framework', 'CFNetwork', '-framework', 'Security', '-framework', 'SystemConfiguration', '-framework', 'AVFoundation', '-framework', 'AudioToolbox', '-framework', 'GLKit', '-framework', 'OpenGLES', '-framework', 'QuartzCore', '-framework', 'CoreMedia', '-framework', 'CoreVideo', '-framework', 'VideoToolbox']' returned non-zero exit status 1
> > > ninja: build stopped: subcommand failed
> > 
> > Hmm, I fail to reproduce the linker error when trying the patch you sent in [1].
> > Have you synced your checkout to the latest revision?
> 
> Ah, sorry. I see now you were building for the simulator.
> 
> The issue should be fixed by adding `peerconnectionfactory_base_objc` to the list of deps for the test target.

Yesterday, I've managed to compile and link for ARM, but unable to run test, because I've worked remotely over SSH and don't know how to run test on ARM devices in such remote environment to see if test actually failed and then fixed.
Today, I've tried to launch test on ARM device from XCode and I'm getting error from XCode that says "Logic Testing on iOS devices is not supported. You can run logic tests on the Simulator.", that's why I probably compiled over x64 simulator initially (I've just really forgot the reasoning over time).
Adding ":peerconnectionfactory_base_objc" to the deps of "sdk_unittests" target fixed compilation (but why it was ok for ARM?).
I'm new to GN and it looks a bit strange, that "sdk_unittests" depends on target ":sdk_unittests_sources", which already has ":peerconnectionfactory_base_objc" among dependencies (there are many of them in "sdk_unittests_sources"), but these dependencies are not "inherited" (only public_deps are inherited?), so it sounds like the test target should duplicate some of the dependencies from "sdk_unittests_sources" source set.

I've finally managed to run XCTests on iOS simulator. I've observed a slight difference in ObjC runtime behavior: previously releasing peer connection and then factory caused the crash, but in XCTest environment on Simualtor it's no longer the case. So I've updated test and explicitly release last reference to factory before releasing reference to peer connection. The test started to crash and got fixed with my change.

Patch-set: 3