Update patch set 1
Patch Set 1:

Dry run: Failed builds:
  luci.webrtc.try/win_x64_msvc_rel JOB_FAILED https://cr-buildbucket.appspot.com/build/8844979912602495584
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [121/428] CXX obj/modules/audio_processing/agc/agc_unittests/clipping_predictor_unittest.obj
    FAILED: obj/modules/audio_processing/agc/agc_unittests/clipping_predictor_unittest.obj
    ninja -t msvc -e environment.x64 -- "C:\b\s\w\ir\cache\builder\src\third_party\depot_tools\win_toolc...(too long)
    ../../modules/audio_processing/agc/clipping_predictor_unittest.cc(135): error C7555: use of designated initializers requires at least '/std:c++latest'
    ../../modules/audio_processing/agc/clipping_predictor_unittest.cc(142): error C7555: use of designated initializers requires at least '/std:c++latest'
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output[failure_summary]
  luci.webrtc.try/win_x64_msvc_dbg JOB_FAILED https://cr-buildbucket.appspot.com/build/8844979912602495600
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [92/1080] CXX obj/modules/audio_processing/agc/agc_unittests/clipping_predictor_unittest.obj
    FAILED: obj/modules/audio_processing/agc/agc_unittests/clipping_predictor_unittest.obj
    ninja -t msvc -e environment.x64 -- "C:\b\s\w\ir\cache\builder\src\third_party\depot_tools\win_toolc...(too long)
    ../../modules/audio_processing/agc/clipping_predictor_unittest.cc(135): error C7555: use of designated initializers requires at least '/std:c++latest'
    ../../modules/audio_processing/agc/clipping_predictor_unittest.cc(142): error C7555: use of designated initializers requires at least '/std:c++latest'
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output[failure_summary]

Patch-set: 1
Tag: autogenerated:cq:dry-run