Update patch set 1
Patch Set 1:

Meh, it seems you have to dig into how the licenses are setup as well: android_rel fails with:

ERROR:root:Missing licenses: errorprone
Traceback (most recent call last):
  File "/b/c/b/android_rel/src/tools_webrtc/android/build_aar.py", line 204, in <module>
    sys.exit(main())
  File "/b/c/b/android_rel/src/tools_webrtc/android/build_aar.py", line 200, in main
    args.build_dir)
  File "/b/c/b/android_rel/src/tools_webrtc/android/build_aar.py", line 189, in BuildAar
    GenerateLicenses(license_dir, build_dir, archs)
  File "/b/c/b/android_rel/src/tools_webrtc/android/build_aar.py", line 171, in GenerateLicenses
    builder.GenerateLicenseText(output_dir)
  File "/b/c/b/android_rel/src/tools_webrtc/android/../libs/generate_licenses.py", line 105, in GenerateLicenseText
    raise Exception(error_msg)
Exception: Missing licenses: errorprone

Patch-set: 1
CC: Gerrit User 5087 <5087@58829da1-049c-39fb-b951-ebdcd0984767>
CC: Gerrit User 5017 <5017@58829da1-049c-39fb-b951-ebdcd0984767>