Update patch set 4
Patch Set 4:

Dry run: Try jobs failed on following builders:
  luci.webrtc.try/win_x64_msvc_dbg JOB_FAILED https://ci.chromium.org/b/8898699690828181216
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [15/45] CXX obj/modules/video_coding/video_coding_unittests/nack_module_unittest.obj
    FAILED: obj/modules/video_coding/video_coding_unittests/nack_module_unittest.obj
    ninja -t msvc -e environment.x64 -- "C:\b\s\w\ir\cache\builder\src\third_party\depot_tools\win_toolc...(too long)
    ../../modules/video_coding/nack_module_unittest.cc(220): error C2220: the following warning is treated as an error
    ../../modules/video_coding/nack_module_unittest.cc(220): warning C4334: '<<': result of 32-bit shift implicitly converted to 64 bits (was 64-bit shift intended?)
    ```
    #### More information in raw_io.output[failure_summary]

Patch-set: 4
Tag: autogenerated:cq:dry-run