Unblock auto roller.
Error message:
Traceback (most recent call last):
  File "/b/s/w/ir/cache/builder/src/tools_webrtc/autoroller/roll_deps.py", line 778, in <module>
    sys.exit(main())
  File "/b/s/w/ir/cache/builder/src/tools_webrtc/autoroller/roll_deps.py", line 748, in main
    raise RollError('WebRTC DEPS entries are missing from Chromium: %s.\n'
__main__.RollError: WebRTC DEPS entries are missing from Chromium: ['src/third_party/fuchsia-sdk/sdk'].
Remove them or add them to either WEBRTC_ONLY_DEPS or DONT_AUTOROLL_THESE.

src/third_party/fuchsia-sdk/sdk has been removed from
https://crrev.com/c/3914609.

Change-Id: Ic2b7b39ffd1a3e5fb9bb73ddb1318a5e36b0bc30