Update patch set 1
Patch Set 1:

Dry run: Failed builds:
  luci.webrtc.try/win_x64_msvc_rel JOB_FAILED https://cr-buildbucket.appspot.com/build/8878341284187070288
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [1/56] CXX obj/modules/video_coding/webrtc_vp9_helpers/svc_config.obj
    FAILED: obj/modules/video_coding/webrtc_vp9_helpers/svc_config.obj
    ninja -t msvc -e environment.x64 -- "C:\b\s\w\ir\cache\builder\src\third_party\depot_tools\win_toolc...(too long)
    ../../modules/video_coding/codecs/vp9/svc_config.cc(83): error C2220: the following warning is treated as an error
    ../../modules/video_coding/codecs/vp9/svc_config.cc(83): warning C4334: '<<': result of 32-bit shift implicitly converted to 64 bits (was 64-bit shift intended?)
    ```
    #### More information in raw_io.output[failure_summary]

Patch-set: 1
Tag: autogenerated:cq:dry-run