Update patch set 1
Patch Set 1:

Patrik, PTAL.

I am not sure what is going on here, the error is:

Downloading files in C:\b\s\w\ir\cache\builder\src\third_party\webrtc\rtc_tools\testing...
Deleting `C:\b\s\w\ir\cache\builder\src\third_party\webrtc\rtc_tools\testing\webrtc_apprtc_browsertest\apprtc`.
`C:\b\s\w\ir\cache\builder\src\third_party\webrtc\rtc_tools\testing\webrtc_apprtc_browsertest\apprtc` does not exist.
Unzipping C:\b\s\w\ir\cache\builder\src\third_party\webrtc\rtc_tools\testing\prebuilt_apprtc.zip in C:\b\s\w\ir\cache\builder\src\third_party\webrtc\rtc_tools\testing\webrtc_apprtc_browsertest.
Traceback (most recent call last):
  File "C:\b\s\w\ir\cache\builder\src\third_party\webrtc\rtc_tools\testing\download_apprtc.py", line 58, in <module>
    sys.exit(main(sys.argv))
  File "C:\b\s\w\ir\cache\builder\src\third_party\webrtc\rtc_tools\testing\download_apprtc.py", line 45, in main
    utils.UnpackArchiveTo(apprtc_zip_path, output_dir)
  File "C:\b\s\w\ir\cache\builder\src\third_party\webrtc\rtc_tools\testing\utils.py", line 94, in UnpackArchiveTo
    _UnzipArchiveTo(archive_path, output_dir)
  File "C:\b\s\w\ir\cache\builder\src\third_party\webrtc\rtc_tools\testing\utils.py", line 103, in _UnzipArchiveTo
    zip_file.extractall(output_dir)
  File "C:\b\s\w\ir\cipd_bin_packages\cpython\bin\Lib\zipfile.py", line 1043, in extractall
    self.extract(zipinfo, path, pwd)
  File "C:\b\s\w\ir\cipd_bin_packages\cpython\bin\Lib\zipfile.py", line 1031, in extract
    return self._extract_member(member, path, pwd)
  File "C:\b\s\w\ir\cipd_bin_packages\cpython\bin\Lib\zipfile.py", line 1086, in _extract_member
    file(targetpath, "wb") as target:
IOError: [Errno 2] No such file or directory: 'C:\\b\\s\\w\\ir\\cache\\builder\\src\\third_party\\webrtc\\rtc_tools\\testing\\webrtc_apprtc_browsertest\\apprtc\\temp\\google-cloud-sdk\\platform\\google_appengine\\php\\sdk\\third_party\\vfsstream\\vendor\\mikey179\\vfsStream\\src\\main\\php\\org\\bovigo\\vfs\\vfsStreamContainerIterator.php'


It looks like on Windows the output_dir is not created if it doesn't exist.

Patch-set: 1
Reviewer: Gerrit User 5027 <5027@58829da1-049c-39fb-b951-ebdcd0984767>
Reviewer: Gerrit User 5087 <5087@58829da1-049c-39fb-b951-ebdcd0984767>
Work-in-progress: false