Update patch set 6
Patch Set 6:

(6 comments)

Thx for the review. I addressed all remarks.

I do not think the following build error is due to my patch but maybe I am missing something:

../../modules/desktop_capture/screen_capturer_mac.mm:449:31: error: missing field 'title' initializer [-Werror,-Wmissing-field-initializers]
    screens->push_back({it->id});

Patch-set: 6
Reviewer: Gerrit User 6236 <6236@58829da1-049c-39fb-b951-ebdcd0984767>
Label: Commit-Queue=0