Update patch set 4
Patch Set 4:

Wat. Why does it fail to apply the patch?

First, rewinding head to replay your work on top of it...
Applying: Moved project configs to infra/config branch
error: Failed to merge in the changes.
Using index info to reconstruct a base tree...
Falling back to patching base and 3-way merge...
Auto-merging README.md
CONFLICT (add/add): Merge conflict in README.md
Patch failed at 0001 Moved project configs to infra/config branch
The copy of the patch that failed is found in: .git/rebase-apply/patch
When you have resolved this problem, run "git rebase --continue".
If you prefer to skip this patch, run "git rebase --skip" instead.
To check out the original branch and stop rebasing, run "git rebase --abort".

Looks like it's attempting to apply the branch history to my patch, rather than the other way around (!?!?) What I did was basically

mkdir config
cd config
git init
git remote add origin https://webrtc.googlesource.com/src
git fetch origin infra/config
git reset --hard origin/infra/config
git config depot-tools.upstream origin/infra/config
git new-branch cr_buildbucket_sync
# hackhackhack
git commit -a
git cl upload

Patch-set: 4
Reviewer: Gerrit User 5027 <5027@58829da1-049c-39fb-b951-ebdcd0984767>
Label: Commit-Queue=0