Update patch set 1
Patch Set 1:

Ptal, this fixes the following compile error with g++ 5.4:

FAILED: obj/third_party/webrtc/api/audio_frame_api/audio_frame.o 
g++ -MMD -MF obj/third_party/webrtc/api/audio_frame_api/audio_frame.o.d -DV8_DEPRECATION_WARNINGS -DUSE_UDEV -DUSE_AURA=1 -DUSE_NSS_CERTS=1 -DUSE_X11=1 -DFULL_SAFE_BROWSING -DSAFE_BROWSING_CSD -DSAFE_BROWSING_DB_LOCAL -DCHROMIUM_BUILD -DFIELDTRIAL_TESTING_ENABLED -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_DEBUG -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DWTF_USE_DYNAMIC_ANNOTATIONS=1 -D_GLIBCXX_DEBUG=1 -DWEBRTC_ENABLE_PROTOBUF=0 -DWEBRTC_INCLUDE_INTERNAL_AUDIO_DEVICE -DHAVE_SCTP -DUSE_BUILTIN_SW_CODECS -DWEBRTC_NON_STATIC_TRACE_EVENT_HANDLERS=0 -DWEBRTC_POSIX -DWEBRTC_LINUX -I../.. -Igen -I../../third_party/webrtc -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -funwind-tables -fPIC -pipe -B../../third_party/binutils/Linux_x64/Release/bin -pthread -m64 -march=x86-64 -Wall -Werror -Wno-unused-local-typedefs -Wno-maybe-uninitialized -Wno-deprecated-declarations -fno-delete-null-pointer-checks -Wno-missing-field-initializers -Wno-unused-parameter -O0 -fno-omit-frame-pointer -g2 -gsplit-dwarf -fvisibility=hidden -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wno-strict-overflow -std=gnu++11 -Wno-narrowing -fno-exceptions -fno-rtti -fvisibility-inlines-hidden -Wnon-virtual-dtor -Woverloaded-virtual -c ../../third_party/webrtc/api/audio/audio_frame.cc -o obj/third_party/webrtc/api/audio_frame_api/audio_frame.o
../../third_party/webrtc/api/audio/audio_frame.cc: In member function ‘void webrtc::AudioFrame::UpdateFrame(uint32_t, const int16_t*, size_t, int, webrtc::AudioFrame::SpeechType, webrtc::AudioFrame::VADActivity, size_t)’:
../../third_party/webrtc/api/audio/audio_frame.cc:60:49: error: ‘memcpy’ was not declared in this scope
     memcpy(data_, data, sizeof(int16_t) * length);
                                                 ^
../../third_party/webrtc/api/audio/audio_frame.cc: In member function ‘void webrtc::AudioFrame::CopyFrom(const webrtc::AudioFrame&)’:
../../third_party/webrtc/api/audio/audio_frame.cc:83:55: error: ‘memcpy’ was not declared in this scope
     memcpy(data_, src.data(), sizeof(int16_t) * length);
                                                       ^
../../third_party/webrtc/api/audio/audio_frame.cc: In member function ‘int16_t* webrtc::AudioFrame::mutable_data()’:
../../third_party/webrtc/api/audio/audio_frame.cc:108:39: error: ‘memset’ was not declared in this scope
     memset(data_, 0, kMaxDataSizeBytes);
                                       ^
../../third_party/webrtc/api/audio/audio_frame.cc: In member function ‘webrtc::AudioFrame& webrtc::AudioFrame::operator+=(const webrtc::AudioFrame&)’:
../../third_party/webrtc/api/audio/audio_frame.cc:162:72: error: ‘memcpy’ was not declared in this scope
              sizeof(int16_t) * rhs.samples_per_channel_ * num_channels_);

Patch-set: 1
Reviewer: Gerrit User 5116 <5116@58829da1-049c-39fb-b951-ebdcd0984767>
Reviewer: Gerrit User 5889 <5889@58829da1-049c-39fb-b951-ebdcd0984767>
Work-in-progress: false