Fix iwyu error introduced recently.
This fixes a build error introduced by:
https://webrtc-review.googlesource.com/c/src/+/349001

bot:
https://ci.chromium.org/ui/p/chromium/builders/webrtc.fyi/WebRTC%20Chromium%20FYI%20ios-device

Error:

../../third_party/webrtc/api/video_codecs/libaom_av1_encoder_factory.cc:494:27: error: expected ';' after expression
494 |   rtc::SimpleStringBuilder sb(buf);
|                           ^
|                           ;
../../third_party/webrtc/api/video_codecs/libaom_av1_encoder_factory.cc:494:8: error: no member named 'SimpleStringBuilder' in namespace 'rtc'

Bug: none
Change-Id: I020040f367005ab56068cf4356e5effb380b7200