Update patch set 10
Patch Set 10:

Failed builds:
  luci.webrtc.try/win_x86_msvc_rel JOB_FAILED https://cr-buildbucket.appspot.com/build/8844179970739499792
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [125/425] CXX obj/modules/audio_processing/agc/agc_unittests/agc_manager_direct_unittest.obj
    FAILED: obj/modules/audio_processing/agc/agc_unittests/agc_manager_direct_unittest.obj
    ninja -t msvc -e environment.x86 -- "C:\b\s\w\ir\cache\builder\src\third_party\depot_tools\win_toolc...(too long)
    ../../modules/audio_processing/agc/agc_manager_direct_unittest.cc(920): error C7555: use of designated initializers requires at least '/std:c++latest'
    ../../modules/audio_processing/agc/agc_manager_direct_unittest.cc(932): error C7555: use of designated initializers requires at least '/std:c++latest'
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output[failure_summary]

Patch-set: 10
Tag: autogenerated:cq:full-run