Update patch set 7
Patch Set 7:

Dry run: Failed builds:
  luci.webrtc.try/win_x86_msvc_rel JOB_FAILED https://cr-buildbucket.appspot.com/build/8844278674753643248
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [97/699] CXX obj/modules/audio_processing/agc/clipping_predictor_evaluator/clipping_predictor_evaluator.obj
    FAILED: obj/modules/audio_processing/agc/clipping_predictor_evaluator/clipping_predictor_evaluator.obj
    ninja -t msvc -e environment.x86 -- "C:\b\s\w\ir\cache\builder\src\third_party\depot_tools\win_toolc...(too long)
    ../../modules/audio_processing/agc/clipping_predictor_evaluator.cc(50): error C7555: use of designated initializers requires at least '/std:c++latest'
    ```
    #### More information in raw_io.output[failure_summary]

Patch-set: 7
Tag: autogenerated:cq:dry-run