Update patch set 6
Patch Set 6:

> Patch Set 6:
> 
> error: duplicate symbol: base::android::LazyGetClass(_JNIEnv*, char const*, std::__ndk1::atomic<_jclass*>*)
> 
> Makes sense, I guess... I should have checked this. But how to solve that?

Can you try to exclude all Chromium Android code from our build? I don't think we should depend on that.

Patch-set: 6
Reviewer: Gerrit User 5112 <5112@58829da1-049c-39fb-b951-ebdcd0984767>