Update patch set 1
Patch Set 1:

This CL has failed the run. Reason:

Failed Tryjobs:
* [webrtc/try/android_arm64_rel](https://cr-buildbucket.appspot.com/build/8746076842032027809). Summary ([view all results](https://webrtc-review.googlesource.com/c/353520?checksPatchset=1&tab=checks)):

---
#### Step _generate_build_files_ failed. Error logs are shown below:
```
ERROR at //base/allocator/partition_allocator/partition_alloc.gni:34:44: Undefined identifier
    current_cpu == "arm64" && is_clang && !is_asan && (is_linux || is_android)
                                           ^------
See //base/allocator/allocator.gni:5:1: whence it was imported.
import("//base/allocator/partition_allocator/partition_alloc.gni")
^----------------------------------------------------------------
See //base/BUILD.gn:20:1: whence it was imported.
import("//base/allocator/allocator.gni")
^--------------------------------------
See //testing/android/native_test/BUILD.gn:21:5: which caused the file to be included.
    "//base",
    ^-------
```
#### More information can be found in the stdout.

---
* [webrtc/try/android_arm_more_configs](https://cr-buildbucket.appspot.com/build/8746076842032027777). Summary ([view all results](https://webrtc-review.googlesource.com/c/353520?checksPatchset=1&tab=checks)):

---
#### Step _generate_build_files_ failed. Error logs are shown below:
```
ERROR at //base/allocator/partition_allocator/src/partition_alloc/BUILD.gn:239:26: Undefined identifier in string expansion.
    "PA_IS_CAST_ANDROID=$is_cast_android",
                         ^--------------
"is_cast_android" is not currently in scope.
See //base/allocator/partition_allocator/BUILD.gn:7:19: which caused the file to be included.
  public_deps = [ "src/partition_alloc:raw_ptr" ]
                  ^----------------------------
```
#### More information can be found in the stdout.

---
* [webrtc/try/android_arm_rel](https://cr-buildbucket.appspot.com/build/8746076842032027761). Summary ([view all results](https://webrtc-review.googlesource.com/c/353520?checksPatchset=1&tab=checks)):

---
#### Step _generate_build_files_ failed. Error logs are shown below:
```
ERROR at //base/allocator/partition_allocator/src/partition_alloc/BUILD.gn:239:26: Undefined identifier in string expansion.
    "PA_IS_CAST_ANDROID=$is_cast_android",
                         ^--------------
"is_cast_android" is not currently in scope.
See //base/allocator/partition_allocator/BUILD.gn:7:19: which caused the file to be included.
  public_deps = [ "src/partition_alloc:raw_ptr" ]
                  ^----------------------------
```
#### More information can be found in the stdout.

---
* [webrtc/try/android_compile_arm_rel](https://cr-buildbucket.appspot.com/build/8746076842032027697). Summary ([view all results](https://webrtc-review.googlesource.com/c/353520?checksPatchset=1&tab=checks)):

---
#### Step _generate_build_files_ failed. Error logs are shown below:
```
ERROR at //base/allocator/partition_allocator/src/partition_alloc/BUILD.gn:239:26: Undefined identifier in string expansion.
    "PA_IS_CAST_ANDROID=$is_cast_android",
                         ^--------------
"is_cast_android" is not currently in scope.
See //base/allocator/partition_allocator/BUILD.gn:7:19: which caused the file to be included.
  public_deps = [ "src/partition_alloc:raw_ptr" ]
                  ^----------------------------
```
#### More information can be found in the stdout.

---
* [webrtc/try/android_compile_x64_dbg](https://cr-buildbucket.appspot.com/build/8746076842032027681). Summary ([view all results](https://webrtc-review.googlesource.com/c/353520?checksPatchset=1&tab=checks)):

---
#### Step _generate_build_files_ failed. Error logs are shown below:
```
ERROR at //base/allocator/partition_allocator/src/partition_alloc/BUILD.gn:239:26: Undefined identifier in string expansion.
    "PA_IS_CAST_ANDROID=$is_cast_android",
                         ^--------------
"is_cast_android" is not currently in scope.
See //base/allocator/partition_allocator/BUILD.gn:7:19: which caused the file to be included.
  public_deps = [ "src/partition_alloc:raw_ptr" ]
                  ^----------------------------
```
#### More information can be found in the stdout.

---
* [webrtc/try/android_compile_x86_rel](https://cr-buildbucket.appspot.com/build/8746076842032027649). Summary ([view all results](https://webrtc-review.googlesource.com/c/353520?checksPatchset=1&tab=checks)):

---
#### Step _generate_build_files_ failed. Error logs are shown below:
```
ERROR at //base/allocator/partition_allocator/src/partition_alloc/BUILD.gn:239:26: Undefined identifier in string expansion.
    "PA_IS_CAST_ANDROID=$is_cast_android",
                         ^--------------
"is_cast_android" is not currently in scope.
See //base/allocator/partition_allocator/BUILD.gn:7:19: which caused the file to be included.
  public_deps = [ "src/partition_alloc:raw_ptr" ]
                  ^----------------------------
```
#### More information can be found in the stdout.

---
* [webrtc/try/ios_api_framework](https://cr-buildbucket.appspot.com/build/8746076842032027617). Summary ([view all results](https://webrtc-review.googlesource.com/c/353520?checksPatchset=1&tab=checks)):

---
Step('build') (retcode: 1)

---
* [webrtc/try/ios_dbg_simulator](https://cr-buildbucket.appspot.com/build/8746076842032027569). Summary ([view all results](https://webrtc-review.googlesource.com/c/353520?checksPatchset=1&tab=checks)):

---
#### Step _compile_ failed. Error logs are shown below:
```
[2695/7322] CC obj/third_party/libaom/libaom_intrinsics_avx2/resize_avx2.o
FAILED: obj/third_party/libaom/libaom_intrinsics_avx2/resize_avx2.o
../../buildtools/reclient/rewrapper -cfg=../../buildtools/reclient_cfgs/chromium-browser-clang/rewra...(too long)
../../third_party/libaom/source/libaom/av1/common/x86/resize_avx2.c:540:5: error: call to undeclared function 'av1_resize_horz_dir_sse2'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
540 |     av1_resize_horz_dir_sse2(input, in_stride, intbuf, height, filtered_length,
|     ^
1 error generated.
```
#### More information in [failure_summary](https://logs.chromium.org/logs/webrtc/buildbucket/cr-buildbucket/8746076842032027569/+/u/compile/raw_io.output_text_failure_summary_)

---
* [webrtc/try/linux_asan](https://cr-buildbucket.appspot.com/build/8746076842032027553). Summary ([view all results](https://webrtc-review.googlesource.com/c/353520?checksPatchset=1&tab=checks)):

---
#### Step _compile_ failed. Error logs are shown below:
```
[2518/6792] CC obj/third_party/libaom/libaom_intrinsics_avx2/resize_avx2.o
FAILED: obj/third_party/libaom/libaom_intrinsics_avx2/resize_avx2.o
../../buildtools/reclient/rewrapper -cfg=../../buildtools/reclient_cfgs/chromium-browser-clang/rewra...(too long)
../../third_party/libaom/source/libaom/av1/common/x86/resize_avx2.c:540:5: error: call to undeclared function 'av1_resize_horz_dir_sse2'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
540 |     av1_resize_horz_dir_sse2(input, in_stride, intbuf, height, filtered_length,
|     ^
1 error generated.
```
#### More information in [failure_summary](https://logs.chromium.org/logs/webrtc/buildbucket/cr-buildbucket/8746076842032027553/+/u/compile/raw_io.output_text_failure_summary_)

---
* [webrtc/try/linux_compile_dbg](https://cr-buildbucket.appspot.com/build/8746076842032027457). Summary ([view all results](https://webrtc-review.googlesource.com/c/353520?checksPatchset=1&tab=checks)):

---
#### Step _compile_ failed. Error logs are shown below:
```
[2639/5318] CC obj/third_party/libaom/libaom_intrinsics_avx2/resize_avx2.o
FAILED: obj/third_party/libaom/libaom_intrinsics_avx2/resize_avx2.o
../../buildtools/reclient/rewrapper -cfg=../../buildtools/reclient_cfgs/chromium-browser-clang/rewra...(too long)
../../third_party/libaom/source/libaom/av1/common/x86/resize_avx2.c:540:5: error: call to undeclared function 'av1_resize_horz_dir_sse2'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
540 |     av1_resize_horz_dir_sse2(input, in_stride, intbuf, height, filtered_length,
|     ^
1 error generated.
```
#### More information in [failure_summary](https://logs.chromium.org/logs/webrtc/buildbucket/cr-buildbucket/8746076842032027457/+/u/compile/raw_io.output_text_failure_summary_)

---
* [webrtc/try/linux_libfuzzer_rel](https://cr-buildbucket.appspot.com/build/8746076842032027409). Summary ([view all results](https://webrtc-review.googlesource.com/c/353520?checksPatchset=1&tab=checks)):

---
#### Step _generate_build_files_ failed. Error logs are shown below:
```
ERROR at //base/allocator/partition_allocator/partition_alloc.gni:363:59: Undefined identifier
    (is_linux || is_chromeos) && current_cpu == "x64" && !is_cronet_build
                                                          ^--------------
See //base/allocator/allocator.gni:5:1: whence it was imported.
import("//base/allocator/partition_allocator/partition_alloc.gni")
^----------------------------------------------------------------
See //base/BUILD.gn:20:1: whence it was imported.
import("//base/allocator/allocator.gni")
^--------------------------------------
See //testing/libfuzzer/BUILD.gn:156:5: which caused the file to be included.
    "//base",
    ^-------
```
#### More information can be found in the stdout.

---
* [webrtc/try/linux_rel](https://cr-buildbucket.appspot.com/build/8746076842032027361). Summary ([view all results](https://webrtc-review.googlesource.com/c/353520?checksPatchset=1&tab=checks)):

---
#### Step _compile_ failed. Error logs are shown below:
```
[2654/5318] CC obj/third_party/libaom/libaom_intrinsics_avx2/resize_avx2.o
FAILED: obj/third_party/libaom/libaom_intrinsics_avx2/resize_avx2.o
../../buildtools/reclient/rewrapper -cfg=../../buildtools/reclient_cfgs/chromium-browser-clang/rewra...(too long)
../../third_party/libaom/source/libaom/av1/common/x86/resize_avx2.c:540:5: error: call to undeclared function 'av1_resize_horz_dir_sse2'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
540 |     av1_resize_horz_dir_sse2(input, in_stride, intbuf, height, filtered_length,
|     ^
1 error generated.
```
#### More information in [failure_summary](https://logs.chromium.org/logs/webrtc/buildbucket/cr-buildbucket/8746076842032027361/+/u/compile/raw_io.output_text_failure_summary_)

---
* [webrtc/try/linux_x86_rel](https://cr-buildbucket.appspot.com/build/8746076842032027281). Summary ([view all results](https://webrtc-review.googlesource.com/c/353520?checksPatchset=1&tab=checks)):

---
#### Step _compile_ failed. Error logs are shown below:
```
[2759/6904] CC obj/third_party/libaom/libaom_intrinsics_avx2/resize_avx2.o
FAILED: obj/third_party/libaom/libaom_intrinsics_avx2/resize_avx2.o
../../buildtools/reclient/rewrapper -cfg=../../buildtools/reclient_cfgs/chromium-browser-clang/rewra...(too long)
../../third_party/libaom/source/libaom/av1/common/x86/resize_avx2.c:540:5: error: call to undeclared function 'av1_resize_horz_dir_sse2'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
540 |     av1_resize_horz_dir_sse2(input, in_stride, intbuf, height, filtered_length,
|     ^
1 error generated.
```
#### More information in [failure_summary](https://logs.chromium.org/logs/webrtc/buildbucket/cr-buildbucket/8746076842032027281/+/u/compile/raw_io.output_text_failure_summary_)

---
* [webrtc/try/mac_asan](https://cr-buildbucket.appspot.com/build/8746076842032027265). Summary ([view all results](https://webrtc-review.googlesource.com/c/353520?checksPatchset=1&tab=checks)):

---
#### Step _compile_ failed. Error logs are shown below:
```
[2964/6893] CC obj/third_party/libaom/libaom_intrinsics_avx2/resize_avx2.o
FAILED: obj/third_party/libaom/libaom_intrinsics_avx2/resize_avx2.o
../../buildtools/reclient/rewrapper -cfg=../../buildtools/reclient_cfgs/chromium-browser-clang/rewra...(too long)
../../third_party/libaom/source/libaom/av1/common/x86/resize_avx2.c:540:5: error: call to undeclared function 'av1_resize_horz_dir_sse2'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
540 |     av1_resize_horz_dir_sse2(input, in_stride, intbuf, height, filtered_length,
|     ^
1 error generated.
```
#### More information in [failure_summary](https://logs.chromium.org/logs/webrtc/buildbucket/cr-buildbucket/8746076842032027265/+/u/compile/raw_io.output_text_failure_summary_)

---

Patch-set: 1
Tag: autogenerated:cq:full-run:1717488164