Update patch set 2
Patch Set 2:

Dry run: Failed builds:
  luci.webrtc.try/win_x86_msvc_dbg JOB_FAILED https://cr-buildbucket.appspot.com/build/8844467866990133456
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [1/97] CXX obj/modules/rtp_rtcp/rtp_rtcp/rtcp_sender.obj
    FAILED: obj/modules/rtp_rtcp/rtp_rtcp/rtcp_sender.obj
    ninja -t msvc -e environment.x86 -- "C:\b\s\w\ir\cache\builder\src\third_party\depot_tools\win_toolc...(too long)
    ../../modules/rtp_rtcp/source/rtcp_sender.cc(171): error C7555: use of designated initializers requires at least '/std:c++latest'
    [2/97] CXX obj/modules/rtp_rtcp/rtp_rtcp/rtp_rtcp_impl2.obj
    FAILED: obj/modules/rtp_rtcp/rtp_rtcp/rtp_rtcp_impl2.obj
    ninja -t msvc -e environment.x86 -- "C:\b\s\w\ir\cache\builder\src\third_party\depot_tools\win_toolc...(too long)
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output[failure_summary]
  luci.webrtc.try/win_x86_msvc_dbg JOB_FAILED https://cr-buildbucket.appspot.com/build/8844467247330171040
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [1/96] CXX obj/modules/rtp_rtcp/rtp_rtcp_legacy/rtp_rtcp_impl.obj
    FAILED: obj/modules/rtp_rtcp/rtp_rtcp_legacy/rtp_rtcp_impl.obj
    ninja -t msvc -e environment.x86 -- "C:\b\s\w\ir\cache\builder\src\third_party\depot_tools\win_toolc...(too long)
    ../../modules/rtp_rtcp/source/rtp_rtcp_impl.cc(62): error C7555: use of designated initializers requires at least '/std:c++latest'
    [2/96] CXX obj/modules/rtp_rtcp/rtp_rtcp/rtp_rtcp_impl2.obj
    FAILED: obj/modules/rtp_rtcp/rtp_rtcp/rtp_rtcp_impl2.obj
    ninja -t msvc -e environment.x86 -- "C:\b\s\w\ir\cache\builder\src\third_party\depot_tools\win_toolc...(too long)
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output[failure_summary]

Patch-set: 2
Tag: autogenerated:cq:dry-run