Update patch set 1
Patch Set 1:

Dry run: Try jobs failed on following builders:
  luci.webrtc.try/win_x64_msvc_rel JOB_FAILED https://ci.chromium.org/b/8888727220942759200
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [44/138] CXX obj/api/voip/test/audio_ingress_unittests/audio_ingress_unittest.obj
    FAILED: obj/api/voip/test/audio_ingress_unittests/audio_ingress_unittest.obj
    ninja -t msvc -e environment.x64 -- "C:\b\s\w\ir\cache\builder\src\third_party\depot_tools\win_toolc...(too long)
    ../../api/voip/test/audio_ingress_unittest.cc(180): error C3493: 'kNtpTimestamp' cannot be implicitly captured because no default capture mode has been specified
    ../../api/voip/test/audio_ingress_unittest.cc(181): error C2664: 'void webrtc::AudioIngress::SetNtpEstimator(std::function<int64_t (uint32_t)>)': cannot convert argument 1 from 'int' to 'std::function<int64_t (uint32_t)>'
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output[failure_summary]

Patch-set: 1
Tag: autogenerated:cq:dry-run