Update patch set 6
Patch Set 6:

RevisionConflictException: Failed to submit 1 change due to the following problems:
Change 99304: Change 99304 is work in progress

Patch-set: 6
Tag: autogenerated:cq:full-run