Update patch set 1
Patch Set 1:

> Patch Set 1:
> 
> > Patch Set 1:
> > 
> > Should I skip the presubmit?
> > 
> > I think the error:
> > Error: the following files need to be regenerated: luci-scheduler.cfg.
> >   Run `lucicfg generate "config.star"` to update them.
> > 
> > is caused by the fact that I am not adding a CI bot?
> 
> No. The presubmit is likely correct.
> 
> Just do what it says?

I have tried but the lucicfg doesn't regenerate luci-scheduler.cfg  (see below). I suspect my change doesn't affect CI, so there no need to schedule anything from LUCI? https://webrtc.googlesource.com/src/+/refs/heads/infra/config/luci-scheduler.cfg mentions only CI, cron and perf.

----

$ git cl upload
Running presubmit upload checks ...

** Presubmit ERRORS **
lucicfg validate "config.star" (0.62s) failed
Error: the following files need to be regenerated: luci-scheduler.cfg.
  Run `lucicfg generate "config.star"` to update them.


Presubmit checks took 3.8s to calculate.

Was the presubmit check useful? If not, run "git cl presubmit -v"
to figure out which PRESUBMIT.py was run, then run git blame
on the file to figure out who to ask for help.

$ lucicfg generate "config.star"
[P230917 10:27:47.128 generate.go:91 I] Generating configs...

$ git status 
On branch component-build-trybots
Your branch is ahead of 'origin/infra/config' by 2 commits.
  (use "git push" to publish your local commits)

nothing to commit, working tree clean

Patch-set: 1
Reviewer: Gerrit User 5087 <5087@58829da1-049c-39fb-b951-ebdcd0984767>
Label: Commit-Queue=0