Update patch set 3
Patch Set 3:

This CL has failed the run. Reason:

Failed Tryjobs:
* [webrtc/try/linux_msan](https://cr-buildbucket.appspot.com/build/8749568756918386897). Summary ([view all results](https://webrtc-review.googlesource.com/c/348800?checksPatchset=3&tab=checks)):

---
1 Test Suite(s) failed.

**video_engine_tests** failed because of:

- AudioFrameOperationsTest.AddingMutedToXGivesX

---
* [webrtc/try/win_chromium_compile](https://cr-buildbucket.appspot.com/build/8749568756918386641). Summary ([view all results](https://webrtc-review.googlesource.com/c/348800?checksPatchset=3&tab=checks)):

---
#### Step _compile (with patch)_ failed. Error logs are shown below:
```
[25233/45077] CXX obj/chrome/browser/ui/ui/startup_browser_creator_impl.obj
FAILED: obj/chrome/browser/ui/ui/startup_browser_creator_impl.obj
..\..\buildtools\reclient\rewrapper -cfg=..\..\buildtools\reclient_cfgs\chromium-browser-clang\rewra...(too long)
../../chrome/browser/ui/startup/startup_browser_creator_impl.cc(568,50): error: no member named 'GetOnboardingTabs' in 'StartupTabProvider'
568 |           StartupTabs onboarding_tabs = provider.GetOnboardingTabs(profile_);
|                                         ~~~~~~~~ ^
1 error generated.
```
#### More information in raw_io.output_text[failure_summary]

---

Patch-set: 3
Tag: autogenerated:cq:dry-run:1714158013
Attention: {"person_ident":"Gerrit User 5508 \u003c5508@58829da1-049c-39fb-b951-ebdcd0984767\u003e","operation":"ADD","reason":"ps#3: Tryjobs failed"}