Always depend on NaCl include_dirs config when targeting NaCl.
Some system headers live in a special directory when targeting NaCl.
Before this CL, WebRTC relies on some "deps" added here and there
in order to propagate the flag
-Inative_client_sdk/src/libraries/third_party/newlib-extras.

This causes brittle builds, for example, when a .cc file which
transitively #includes <arpa/inet.h> is moved to a build target that
doesn't depend on (transitively or not)
//native_client_sdk/src/libraries/nacl_io the build will break with
a similar error:

In file included from ../../third_party/webrtc/rtc_base/fifo_buffer.cc:15:
In file included from ../../third_party/webrtc/rtc_base/thread.h:26:
In file included from ../../third_party/webrtc/rtc_base/message_queue.h:27:
In file included from ../../third_party/webrtc/rtc_base/socket_server.h:15:
In file included from ../../third_party/webrtc/rtc_base/socket_factory.h:14:
In file included from ../../third_party/webrtc/rtc_base/async_socket.h:17:
../../third_party/webrtc/rtc_base/socket.h:17:10: fatal error: 'arpa/inet.h' file not found

Bug: chromium:925028
Change-Id: I5145b80c2ae6969f79fcbfcf93a6b05c8a122746