Update patch set 1
Patch Set 1:

Dry run: Failed builds:
  luci.webrtc.try/android_compile_x86_dbg JOB_FAILED https://cr-buildbucket.appspot.com/build/8820091739656679025
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [935/2515] CXX obj/sdk/android/video_jni/android_video_track_source.o
    FAILED: obj/sdk/android/video_jni/android_video_track_source.o
    /b/s/w/ir/cache/goma/client/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF...(too long)
    ../../sdk/android/src/jni/android_video_track_source.cc:45:7: error: no matching constructor for initialization of 'rtc::AdaptedVideoTrackSource'
    : AdaptedVideoTrackSource(kRequiredResolutionAlignment),
    ^                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output_text[failure_summary]
  luci.webrtc.try/android_compile_arm64_rel JOB_FAILED https://cr-buildbucket.appspot.com/build/8820091739656679073
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [1026/2148] CXX obj/sdk/android/video_jni/android_video_track_source.o
    FAILED: obj/sdk/android/video_jni/android_video_track_source.o
    /b/s/w/ir/cache/goma/client/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF...(too long)
    ../../sdk/android/src/jni/android_video_track_source.cc:45:7: error: no matching constructor for initialization of 'rtc::AdaptedVideoTrackSource'
    : AdaptedVideoTrackSource(kRequiredResolutionAlignment),
    ^                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output_text[failure_summary]
  luci.webrtc.try/mac_compile_dbg JOB_FAILED https://cr-buildbucket.appspot.com/build/8820091739656678577
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [159/521] OBJCXX obj/sdk/native_video/objc_video_track_source.o
    FAILED: obj/sdk/native_video/objc_video_track_source.o
    /opt/s/w/ir/cache/goma/client/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -...(too long)
    ../../sdk/objc/native/src/objc_video_track_source.mm:40:7: error: no matching constructor for initialization of 'rtc::AdaptedVideoTrackSource'
    : AdaptedVideoTrackSource(/* required resolution alignment */ 2),
    ^                                                           ~
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output_text[failure_summary]

Patch-set: 1
Tag: autogenerated:cq:dry-run
Attention: {"person_ident":"Gerrit User 5613 \u003c5613@58829da1-049c-39fb-b951-ebdcd0984767\u003e","operation":"ADD","reason":"ps#1: CQ dry run failed."}