Update patch set 4
Patch Set 4:

Failed builds:
  luci.webrtc.try/win_x86_msvc_dbg JOB_FAILED https://cr-buildbucket.appspot.com/build/8844282190459805568
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [25/251] CXX obj/modules/audio_processing/agc/agc_unittests/clipping_predictor_unittest.obj
    FAILED: obj/modules/audio_processing/agc/agc_unittests/clipping_predictor_unittest.obj
    ninja -t msvc -e environment.x86 -- "C:\b\s\w\ir\cache\builder\src\third_party\depot_tools\win_toolc...(too long)
    ../../modules/audio_processing/agc/clipping_predictor_unittest.cc(334): error C7555: use of designated initializers requires at least '/std:c++latest'
    ```
    #### More information in raw_io.output[failure_summary]

Patch-set: 4
Tag: autogenerated:cq:full-run